### ISSUE TITLE
the columns order in tab Test is different from importing data

### ISSUE THREAD

**Issue by goodtogood** [bhrnjica/anndotnet#54]
Hi,
   thanks for your work. 
recently I was trying Anndotnet and came across some problems.
the columns order in tab Test is different from importing data
I think It's much better we can select or ignore some columns 
when importing from file in Tab Test.   
specifying gpu No. and exporting test result  might be also needed.

![c1](https://user-images.githubusercontent.com/10088733/54074442-80e91a80-42cd-11e9-8add-1ebc8bcabd48.jpg)

![c2](https://user-images.githubusercontent.com/10088733/54074446-87779200-42cd-11e9-9e7f-2932a505aa76.jpg)

**Comment by bhrnjica** [comment]
Hi, 

thank you for reporting this issue. 

The order of the columns in the test page is different than in the raw data. The order of the columns is made so that the first is numeric columns, then categorical columns. This is for the implementation reason.

**Comment by goodtogood** [comment]
I see , thanks.
