### ISSUE TITLE
Explaining example 

### ISSUE THREAD

**Issue by workpioupiou** [bhrnjica/anndotnet#56]
I know it's a lot of time to do that but, is that possible to explain your example. I look at Air Quality and I can't understand how you determine the dimension value of your layer. 

Thank you for the project ! it's a lot of work to do !

**Comment by bhrnjica** [comment]
HI, thanx for the interest in my open source project.

The air-quality example is multiclass classification problem. The label is categorical column consisted of 5 difference class values.

![image](https://user-images.githubusercontent.com/1240016/100268459-60f00380-2f55-11eb-83c5-51d4a79a9e07.png)

So features and label are defined during data preparation. The ML configuration is created based on the data preparation.

Once you setup the data as image shows, creation of MLConfig is completely defined by above data preparation.

![image](https://user-images.githubusercontent.com/1240016/100268875-fdb2a100-2f55-11eb-8087-fb4683f23708.png)


For more information please see the Wiki pages or http://bhrnjica.net/anndotnet
